### ISSUE TITLE
Using local inference results in "Failed generating code: result was truncated: length"

### ISSUE THREAD

**Issue by remmen-io** [gofireflyio/aiac#121]
I'm using a local inference service using huggingface tgi, which is compatible with the openai api.

I get the following error using it with aiac
``` 
aiac get --url="https://deepseek.myinference.ch/v1" --api-key="none" terraform code for a s3 bucket on aws
Failed generating code: result was truncated: length

[R/r]: retry same prompt
[Y/y]: copy to clipboard
[Q/q]: quit
```

Using the inference api with curl or other AI tools works flawless

**Comment by ido50** [comment]
Hi, sorry for the delay. Can you post the full JSON output you get when running the same exact query via curl? It seems the API is telling us it did not return the full generated text.
