### ISSUE TITLE
BUG: Ollama models not selectable - query server for modellist

### ISSUE THREAD

**Issue by chymian** [gofireflyio/aiac#123]
hi, just found your sw and it seems it is, what I was looking for.
unfortuantley I can not try it:

__Problem__
trying to select a local installed ollama model, i.e. like: 
- phi3:3.8b-mini-128k-instruct-q6_K
- granite-code:8b-instruct-q6_K

fails due to hardcoded (and complete out of date list)

__Remedy__
Query modelist from server - it's changing every day!

__BTW__
IMHO, the CLI is very unconfortable b/c of "unusual" parameter order.
pls. make a OLLAMA_MODEL Variable, so we can put it into the environment/config.

**Comment by ido50** [comment]
Hi. Version 5.0.0 should address all of these concerns. Thank you for your feedback. Please refer to the README.md file for updated usage information.
