### ISSUE TITLE
Error: failed sending prompt - insufficient quota

### ISSUE THREAD

**Issue by Y4HYA4** [gofireflyio/aiac#16]
Hello team,

I encountered an error when attempting to run the command aiac get 

The error message I received was:

```
$ aiac get dockerfile for nodejs with comments
Request failed: failed sending prompt: [insufficient_quota] You exceeded your current quota, please check your plan and billing details.
```

I have yet to try the tool, and I'm wondering if there are any restrictions in place right now.

Thanks,

**Comment by liavyona** [comment]
Hi @Y4HYA4 , 
AIAC is a CLI interface to work with OpenAI. Hence you need their token. You're also have a limitation to amount of requests as a free tier user of OpenAI. The error you received came from OpenAI API. You can try later and see if it works for you. By the way, we're working on a solution to overcome such cases.
