### ISSUE TITLE
Installing on Ubuntu CLI : ERROR Obtaining VCS status

### ISSUE THREAD

**Issue by javedkumail** [gofireflyio/aiac#17]
after cloning the repository using git clone command
i ran `go build` command inside aiac directory
it gives
`
javedkumail@DESKTOP-HESPAQG:~/aiac$ go build
go: downloading github.com/alecthomas/kong v0.7.1
go: downloading github.com/adrg/xdg v0.4.0
go: downloading github.com/briandowns/spinner v1.19.0
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/google/uuid v1.1.2
go: downloading github.com/ido50/requests v1.5.0
go: downloading github.com/manifoldco/promptui v0.9.0
go: downloading github.com/mattn/go-colorable v0.1.2
go: downloading github.com/mattn/go-isatty v0.0.16
go: downloading go.uber.org/zap v1.24.0
go: downloading github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
go: downloading golang.org/x/sys v0.0.0-20220811171246-fbc7d0a398ab
go: downloading go.uber.org/atomic v1.10.0
go: downloading go.uber.org/multierr v1.8.0
**error obtaining VCS status: exit status 128**
        Use -buildvcs=false to disable VCS stamping.
`
it gives error obtaining  VCS status

even after running ` go build -buildvcs=false `  i get this 
`
go build github.com/gofireflyio/aiac: copying /tmp/go-build1528433998/b001/exe/a.out: open aiac: permission denied
`

**Comment by liavyona** [comment]
@javedkumail 

can you share `go env` and `go version`?

**Comment by javedkumail** [comment]
> @javedkumail
> 
> can you share `go env` and `go version`?

go version
` go version go1.18.1 linux/amd64 `

go env

![Screenshot 2023-01-25 222644](https://user-images.githubusercontent.com/107232454/214628572-d6853b3f-176e-4b58-9e2b-2ec13bd35880.jpg)

**Comment by giulio-giunta** [comment]
I experienced the same issue.
go env:
`GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/giulio/.cache/go-build"
GOENV="/home/giulio/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/giulio/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/giulio/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/giulio/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/giulio/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3036957518=/tmp/go-build -gno-record-gcc-switches"`

go version:
`go version go1.19.4 linux/amd64`

![image](https://user-images.githubusercontent.com/56529931/215283919-72f877ce-952b-41f1-a828-4e3108644382.png)

**Comment by Andr1500** [comment]
I also have an issue on Ubuntu, when I try to run any command, I have an error: "Command 'aiac' not found, did you mean:"
go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4277354706=/tmp/go-build -gno-record-gcc-switches"

 go version
go version go1.18.1 linux/amd64

my execution of go build:
go: downloading github.com/alecthomas/kong v0.7.1
go: downloading github.com/adrg/xdg v0.4.0
go: downloading github.com/briandowns/spinner v1.19.0
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/google/uuid v1.1.2
go: downloading github.com/ido50/requests v1.5.0
go: downloading github.com/manifoldco/promptui v0.9.0
go: downloading github.com/mattn/go-colorable v0.1.2
go: downloading github.com/mattn/go-isatty v0.0.16
go: downloading go.uber.org/zap v1.24.0
go: downloading golang.org/x/sys v0.0.0-20220811171246-fbc7d0a398ab
go: downloading go.uber.org/atomic v1.10.0
go: downloading go.uber.org/multierr v1.8.0

**Comment by ido50** [comment]
@javedkumail, this seems to have been a temporary issue with the Uber's Go repository. If you're still having issues, please reopen.
