### ISSUE TITLE
Almost all the commands I give aiac don't work?

### ISSUE THREAD

**Issue by jsteinberg-rbi** [gofireflyio/aiac#18]
Sorry for the confusion, but I'm curious why you've decided to publish this now? I'd love to use something like this, but every time I give at an instruction I actually care about it's unable to run it? When I copy and paste use cases from the doc directly it works fine. For example none of these commands have run, though they run trivially on ChatGPT:

```
aiac get python that authenticates to aws

aiac get dockerfile for typescript program that runs terraformer from the command line

aiac get circleci orb for validating terraform json with opa
```

They all return `Request failed: failed sending prompt: [server_error] The server had an error while processing your request. Sorry about that!`

But this works fine:

```
aiac get terraform for AWS EC2
# Create a main.tf file

provider "aws" {
  region     = "us-east-1"
}

resource "aws_instance" "ec2-instance" {
  ami           = "ami-08d798f297f89fce1"
  instance_type = "t2.micro"

  tags = {
    Name = "test-instance"
  }
}
```

So I'm wondering what you're looking for from the community? I'm happy to be an early adopter, but how? I feel like my commands above are correct.

**Comment by jsteinberg-rbi** [comment]
Okay I got the first command to run by changing aws -> AWS?

**Comment by ido50** [comment]
Usually the OpenAI API isn't sensitive to casing, but it's possible that sometimes it misidentifies the context without proper casing. If you're still encountering issues, let us know and we'll see if there's anything we can do on aiac's side (I doubt it). For now, I'm closing.
