### ISSUE TITLE
README says to join Slack, but Slack requires firefly email?

### ISSUE THREAD

**Issue by jsteinberg-rbi** [gofireflyio/aiac#19]
Subject says it all.

**Comment by dilipk8** [comment]
Same point, can we get a slack invite ? How do we join Slack.

**Comment by gmaghera** [comment]
Same goes for the https://aiac.dev/ page and the prominent "Community Support" link at the top, which leads to requesting a Slack signup, that seems to require an account.

**Comment by ido50** [comment]
Seems like Slack support is not an option for us right now. We will review better options and update the README accordingly. I have removed the Slack link for now. Thanks. This Issue tracker is always here if non-immediate support is necessary, but I doubt we'll actually provide immediate support.
