### ISSUE TITLE
`go install` command doesn't work...

### ISSUE THREAD

**Issue by wtanksleyjr** [gofireflyio/aiac#28]
The readme says to run `go install github.com/gofireflyio/aiac/v2`, but that produces an error:
```
go install: version is required when current directory is not in a module
        Try 'go install github.com/gofireflyio/aiac/v2@latest' to install the latest version
```
Attempting the suggested command produces a lot of output (I don't see any errors, looks like warnings) and doesn't add a binary to my `$GOBIN` folder.

**Comment by wtanksleyjr** [comment]
OK, let me correct my mistake: ` install github.com/gofireflyio/aiac/v2@latest` does work. So adding that "@latest" should be the only change needed to fix this. (My basic error -- I had too old of a go version, I think you need go 1.19 or later.)

**Comment by liavyona** [comment]
Thank you @wtanksleyjr
