### ISSUE TITLE
feature request: support Azure OpenAI

### ISSUE THREAD

**Issue by maciej-pa** [gofireflyio/aiac#35]
Working at a corporate behemoth, we are stuck with Azure due to compliance-related reasons, unable to use OpenAI as provided by its creators.

However, as far as I can tell, the OpenAI provided by Azure is supposed to be the same under the hood - could you please consider supporting [Azure OpenAI](https://azure.microsoft.com/en-us/products/cognitive-services/openai-service/) as well?!

**Comment by TheKangaroo** [comment]
I think this was closed by mistake? 
I would love to see this implemented  :)

**Comment by worldofgeese** [comment]
@ido50 can you please reopen this issue? Azure's OpenAI requires [setting an endpoint in addition to the key value](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/quickstart?tabs=command-line&pivots=programming-language-python#retrieve-key-and-endpoint).
