### ISSUE TITLE
Copy to clipboard or directly run CLI?

### ISSUE THREAD

**Issue by christophetd** [gofireflyio/aiac#36]
Would be great to have a feature where you can copy the generated output (e.g. CLI) to the clipboard, to be able to reuse it right away!

**Comment by ido50** [comment]
While there are ways to do that, it's actually not that simple, given the fact that there are multiple possible clipboard, especially on Linux. I think it's better to simply pipe the output to a clipboard-specific tool such as `xclip`:

`aiac get terraform for eks -q | xclip`

We'll give it some more thought, so I'm not closing for now.

**Comment by liavyona** [comment]
@christophetd we just released the copy to clipboard option. Try it out!

**Comment by christophetd** [comment]
amazing!

**Comment by christophetd** [comment]
I'm getting an error:


![image](https://user-images.githubusercontent.com/136675/236167232-3633d24c-6146-475f-abd7-862f8f974f93.png)
