### ISSUE TITLE
aiac doesn't work when installed via brew install on Mac arm

### ISSUE THREAD

**Issue by poparotsy** [gofireflyio/aiac#49]
panic: clipboard: cannot use when CGO_ENABLED=0

goroutine 1 [running]:
golang.design/x/clipboard.initialize(...)
	/home/runner/go/pkg/mod/golang.design/x/clipboard@v0.7.0/clipboard_nocgo.go:9
golang.design/x/clipboard.Init.func1()
	/home/runner/go/pkg/mod/golang.design/x/clipboard@v0.7.0/clipboard.go:107 +0x2c
sync.(*Once).doSlow(0x1400002e480?, 0x140000752b0?)
	/opt/hostedtoolcache/go/1.19.8/x64/src/sync/once.go:74 +0x104
sync.(*Once).Do(...)
	/opt/hostedtoolcache/go/1.19.8/x64/src/sync/once.go:65
golang.design/x/clipboard.Init()
	/home/runner/go/pkg/mod/golang.design/x/clipboard@v0.7.0/clipboard.go:106 +0x3c
main.generateCode({{{0x0, 0x0}}, {{0x140000286c0, 0x33}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, ...}, ...})
	/home/runner/work/aiac/aiac/main.go:147 +0x300
main.main()
	/home/runner/work/aiac/aiac/main.go:75 +0x4d0

--------

CGO_ENABLED=1 # doesn't help

git clone && go build works.

**Comment by dorancemc** [comment]
Same for me on Mac.Intel, installing previous version v.2.2.0. works

**Comment by liavyona** [comment]
@poparotsy and @dorancemc thank you for reporting it.

We solved it in #54 .
