### ISSUE TITLE
encase example vars as {variable}

### ISSUE THREAD

**Issue by wilsonmar** [gofireflyio/aiac#78]
Instead of creating the hcl with values and this note, such as:

`  region = "us-west-2"
`
and
`Note: Make sure to replace the `ami`, `key_name`, and `region` values with your own values.
`
How about defining variables:
`  region = "{region1}"
`
(The number in the variable is when multiple regions are defined, which is typical of production hcl. Some would prefer {primary_region}. So a post-processor could make those changes if the values inserted are consistent.

**Comment by ido50** [comment]
Hi there. Sorry for taking long to respond. I think trying to post-process responses in that way will be error prone, and it's also questionable whether modifying the responses from the provider is a good idea strategically.

We could, theoretically, add wording to the prompts we send to the provider that instruct it to use variables in its responses, but this will use up more tokens. For now, I think it's better to use the chat feature and instruct the provider to return variables.

I'm closing this, as we will not be moving along with this feature.
