### ISSUE TITLE
Mac M2, installed via brew panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rapidarchitect** [gofireflyio/aiac#84]
Following the directions i installed via brew (after brew upgrade) and getting the following error message

ic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x100b22e4c]

goroutine 1 [running]:
github.com/gofireflyio/aiac/v4/libaiac/openai.(*Conversation).Send(0x14000079130, {0x100d3a3b0, 0x140000280f8}, {0x140000239c0, 0x39}, {0x0, 0x0, 0x0?})
	/home/runner/work/aiac/aiac/libaiac/openai/chat.go:65 +0x21c
main.generateCode({{0x100b63033, 0x6}, {{0x0, 0x0}}, {{0x0, 0x0}, {0x14000027c60, 0x19}, {0x0, 0x0}, ...}, ...})
	/home/runner/work/aiac/aiac/main.go:197 +0x470
main.main()
	/home/runner/work/aiac/aiac/main.go:88 +0x4d0

**Comment by den-vasyliev** [comment]
OPENAI_API_KEY is not set

**Comment by rapidarchitect** [comment]
that did the trick. weird that i was trying to use bedrock and it still required the OPENAI_API_KEY

**Comment by ido50** [comment]
How did you try to use bedrock? Did you provide the `-b` flag or did you set the `AIAC_BACKEND` environment variable?

**Comment by rapidarchitect** [comment]
With the -b flag

___________________________
Mike Hjorleifsson
***@***.***

This e-mail and any files transmitted with it are confidential and are intended solely for the use of the
individual entity to whom they are addressed. This communication may contain material protected by the
attorney-client privilege. If you are not the intended recipient or the person responsible for delivering the
e-mail to the intended recipient, be advised that you have received this e-mail in error and that any use,
dissemination, forwarding, printing or copying this e-mail or any file or files transmitted with it is strictly prohibited.
