### ISSUE TITLE
Consider setting backend alternatives via config file, current signature makes for ungainly usage

### ISSUE THREAD

**Issue by gmaghera** [gofireflyio/aiac#91]
When using `aiac` with a different backend, such as Azure OpenAI one has to do something like [this](https://github.com/gofireflyio/aiac/issues/68#issuecomment-1640240475):

`aiac get --api-version="2023-05-15" --url="https://tenant.openai.azure.com/openai/deployments/testdeployment" terraform code for ssm paramter`

The --flags have to go after the `aiac get` piece, and that makes it difficult to use aliases to make the above command shorter.

Could you consider using a config file instead, so we don't have to rely on aliases? Or allow putting the --flags before the subcommand (the only other subcommand I'm aware of wouldn't be impacted by it).

**Comment by VamshikrishnaAluwala** [comment]
Hi 
There is any chance to use a different model apart from the mentioned model? I am unable to access the Llama3, Gemma, and other LLMs. 
How to Access Other  LLM 
Models

**Comment by ido50** [comment]
The model list will no longer be hardcoded in the next release.
